# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=sawinter*5
    ports:
      - 2433:1433

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5022:5022
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    entrypoint: ["/app/wait-for-it.sh", "host.docker.internal:3433", "-t", "10", "--", "dotnet", "WebApi.dll"]


